### ISSUE TITLE
打包的应用不支持修改端口，导致部署访问平台报错

### ISSUE THREAD

**Issue by linda0007** [arextest/deployments#8]
![272188be2a974c1e756486adde189d5](https://user-images.githubusercontent.com/20278174/183034116-e9ffcce1-1e51-4b93-b384-054aaab380f4.png)
![4975ff6bc371a7f5a2698c3c61234f5](https://user-images.githubusercontent.com/20278174/183034144-09dca33f-df92-4a9d-82f0-34a075780b9e.jpg)

**Comment by haibing-wang** [comment]
The arex-mysql component has been removed

**Comment by haibing-wang** [comment]
When  u  updated the docker-compose.yml , such as ports
```
  arex-report-service:
    image: arexadmin01/arex-report:0.2.6
    container_name: arex-report
    restart: always
    ports:
      - '18090:8080'
```
If you  visit the  service's  interface in AREX or Postman, You should update the port to 18090.
The AREX UI visit service by the 8080 port, not 18090
